### PR TITLE
NCRO 2022 data

### PR DESCRIPTION
**Pull request by rosehartman**
Added all of NCRO's 2022 data. I did a few quick checks for dates and times and outliers, but I didn't go over it extensively.

### CODE REVIEW

**Comment by rosehartman** [comment]
Oh, and I didn't realize this pull request never got incorporated. Now I have DOP data too!

**Review by mountaindboz — COMMENTED** [review]
Okay, I think this PR #44 is ready to be merged into `main`. 
@sbashevkin - do you want to review it first?

**Comment by sbashevkin** [comment]
@mountaindboz No I think just you reviewing it is fine, thanks!

**Comment by mountaindboz** [comment]
Okay, great! I'll merge it in now!

**Pull request merged**
